### ISSUE TITLE
"gitLabConnection" is not a valid option. 

### ISSUE THREAD

**Issue by norricorp** [jenkinsci/gitlab-plugin#803] opened 2018-07-16 20:06 UTC
### Context
Gitlab plugin version: 1.5.7
Gitlab version: 11.0.3
Jenkins version: 2.1.30
Job type: Pipeline declarative,

### Logs & Traces
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: 13: Invalid option type "gitLabConnection". Valid option types: [authorizationMatrix, buildDiscarder, catchError, checkoutToSubdirectory, disableConcurrentBuilds, disableResume, durabilityHint, gitlabBuilds, gitlabCommitStatus, newContainerPerStage, overrideIndexTriggers, preserveStashes, retry, script, skipDefaultCheckout, skipStagesAfterUnstable, timeout, timestamps, waitUntil, withContext, withCredentials, withEnv, ws] @ line 13, column 7.
         gitLabConnection('mint-gitlab')

### Problem description

Run replay with changed jenkinsfile, adding
    post {
      failure {
        updateGitlabCommitStatus name: 'build', state: 'failed'
      }
      success {
        updateGitlabCommitStatus name: 'build', state: 'success'
      }
    }
    options {
      gitLabConnection('mint-gitlab')
    }
    triggers {
        gitlab(triggerOnPush: true, triggerOnMergeRequest: false, branchFilterType: 'All')
    }
The gitLabConection information was already in the pipeline job within the GUI setup (under General).
Result was in logs section. It appears that "gitLabConnection" is not a valid option.

I then run the code again, removing the following code
    options {
      gitLabConnection('mint-gitlab')
    }
And now the job completes in Jenkins. And it does update GitLab on completion.

**Comment by omehegan** [comment] 2018-07-17 06:02
Duplicate of #789. Would suggest you wait for me to release 1.5.9, which will have another related fix. See #799.

**Closed as completed by omehegan** 2018-07-17 06:02 UTC
