### ISSUE TITLE
Two or more webhooks produce 'retried builds' in GitLab

### ISSUE THREAD

**Issue by vills** [jenkinsci/gitlab-plugin#249] opened 2016-03-29 12:48 UTC
_Not sure, but it can be a duplicate of #200_

If we use more than one webhook in repository, than builds are recorded in GitLab as 'retried', that isn't true actually. Not sure, but it can be because of field 'Name' (Jenkins) reported by plugin to GitLab instance.

It would be nice to set-up 'Name' field on per job basis in jenkins, that is reported to GitLabCI.

Gitlab version: 8.6. Gitlab 8.1 features enabled in jenkins' job.

Thanks.

**Comment by coder-hugo** [comment] 2016-03-30 15:37
IIRC it's enough if the description of the [commit status](http://doc.gitlab.com/ce/api/commits.html#post-the-build-status-to-a-commit) is different to have a separate build instead of a retried one in the GitLab build list.
So I think we should add the possibility to send a also configurable description to GitLab while updating the status of a commit.

**Comment by vills** [comment] 2016-03-30 16:09
@coder-hugo +1

Anyway, it would be nice to see both 'name' and 'description' as a optional configurable options in job. Cause 'name' add ability to determine job exactly from gitlab's build list.

**Comment by coder-hugo** [comment] 2016-06-23 20:59
Duplicate of #362

**Closed as completed by coder-hugo** 2016-06-23 20:59 UTC
Labels: feature request
