### ISSUE TITLE
[Feature request] Be able to define the stage graph

### ISSUE THREAD

**Issue by christophehenry** [jenkinsci/gitlab-plugin#1035] opened 2020-03-01 19:55 UTC
### Before submitting an issue I have first:

- [x] read the documentation on the [homepage](https://github.com/jenkinsci/gitlab-plugin) 
- [x] searched for similar already existing issue
- [x] confirmed that my GitLab webhook is using the http://JENKINS_URL/project endpoint and not the http://JENKINS_URL/job endpoint

I've searched though the issues but I couldn't find one request that feature so sorry if it already exists. 

Currently, the function `gitlabBuilds` allows to infor Gitlab about the Pipeline stages that are about to be executed. But they appear independent to each other on the pipeline page of Gitlab:

![jenkins](https://user-images.githubusercontent.com/22097904/75632675-cd281b80-5bfe-11ea-8668-a2584b6f1c24.png)

I would be nice if this function allowed to define the stage graph and make Gitlab display the steps like it displays GitlabCi's:

![image](https://user-images.githubusercontent.com/22097904/75632699-052f5e80-5bff-11ea-83d7-a81dfcafe324.png)

**Comment by commodis** [comment] 2020-05-15 15:53
Duplicate of https://github.com/jenkinsci/gitlab-plugin/issues/554

**Closed as completed** 2021-01-18 13:07 UTC
