### ISSUE TITLE
DSL Generated Job missing GitLab notification configuration

### ISSUE THREAD

**Issue by briceo** [jenkinsci/gitlab-plugin#378] opened 2016-07-12 18:51 UTC
## Issue

When using the JobDSL plugin to describe jobs, the resulting generated job is missing GitLab configuration settings (the generated job _has_ the publisher defined, but doesn't work until I manually save the job).
### Context
- **Gitlab plugin version**: 1.3.0
- **Gitlab version**: 8.9.5
- **Jenkins version**: 2.13
### Problem description

A DSL generated job seems to be missing configuration of the GitLab server.  Here is an example job

```
job('example') {
    scm {
        git {
            remote {
                name('master')
                branch('master')
                url('ssh://git@gitlab.server.com:22/example.git')
                credentials('some_user')
            }
            extensions {
                cleanBeforeCheckout()
                relativeTargetDirectory('src')
            }
        }
    }
    triggers {
        gitlabPush {
            buildOnMergeRequestEvents(false)
            buildOnPushEvents(true)
        }
    }
    steps {
        msBuild {
            buildFile('src/some_solution.sln')
            args('/p:Configuration=Release')
            passBuildVariables()
            continueOnBuildFailure(false)
        }
    }
    publishers {
        allowBrokenBuildClaiming()
        chucknorris()
        archiveArtifacts {
            pattern('src/x64/Release/*.dll')
            fingerprint(true)
            allowEmpty(false)
            onlyIfSuccessful()
        }
        gitLabCommitStatusPublisher {
            name('example')
        }
    }
}
```

After generating a job, I can download the `config.xml` of the job, and it is missing the following:

```
<com.dabsquared.gitlabjenkins.connection.GitLabConnectionProperty plugin="gitlab-plugin@1.3.0">
<gitLabConnection>gitlab.server.com</gitLabConnection>
</com.dabsquared.gitlabjenkins.connection.GitLabConnectionProperty>
```

If I execute the generated job, at the end of the console output, I get the message: 

```
Archiving artifacts
Recording fingerprints
No GitLab connection configured
Finished: SUCCESS
```

If I simply open up the configuration of the job, and just save the job (without changing anything), and then download the `config.xml` again, the above mentioned settings now show up correctly, and the job correctly notifies GitLab with the status of the build.  Below is the output of the end of the same build where I have manually saved the job again after generating it:

```
Archiving artifacts
Recording fingerprints
Finished: SUCCESS
```

When I go look at the related repository in GitLab for this job, I now see a build status showing up.

**Comment by omehegan** [comment] 2016-07-12 18:56
Duplicate of https://github.com/jenkinsci/gitlab-plugin/issues/377.

**Closed as completed by omehegan** 2016-07-12 18:56 UTC
