### ISSUE TITLE
Feature Request: Support the SCM Navigator (*Branch Source) type projects

### ISSUE THREAD

**Issue by mkobit** [jenkinsci/gitlab-plugin#465] opened 2016-12-14 16:57 UTC
We currently use Bitbucket Server, with the https://github.com/jenkinsci/bitbucket-branch-source-plugin . This plugin allows us to define a job per Bitbucket Server Project and it will automatically index and build all branches, all PRs, PR notifications, etc. It allows us to define a `Jenkinsfile` in a repository and have it automatically pick it up.

The GitHub plugin (https://wiki.jenkins-ci.org/display/JENKINS/GitHub+Branch+Source+Plugin) also supports the SCMNavigator style of indexing an entire organization.

A big selling point to switch to GitLab would be if there was the same kind of functionality so it is easier for us to migrate our `Jenkinsfile`s from one SCM to another rather than have to immediately switch to using this plugin or using GitLab CI immediately.

### Context
- **Jenkins version**: 2.25
- **Job type**: Organization Job

**Comment by omehegan** [comment] 2016-12-17 05:50
I'll add this as a feature request, but we don't currently have an active maintainer who could implement it. 

cc @dblessing

**Comment by omehegan** [comment] 2017-07-06 05:18
Dupe of #499.

**Closed as completed by omehegan** 2017-07-06 05:18 UTC
Labels: feature request
