### ISSUE TITLE
Plugin not working with multiple SCM configuration.

### ISSUE THREAD

**Issue by skyline00** [jenkinsci/gitlab-plugin#183] opened 2016-01-20 12:39 UTC
Hey,
I'm using this plugin:
https://wiki.jenkins-ci.org/display/JENKINS/Multiple+SCMs+Plugin

I have 4 repositories configured in one job. The first one is checking out properly, but problem starts with other ones. I guess gitlab webhook is sending commit hash from one repository only and tries to use it with all of them. This is the error message:
13:31:36 FATAL: Command "git rev-parse 9f3840b5f10bd7e9d4a7bde849aad96e9926d827^{commit}" returned status code 128:
13:31:36 stdout: 9f3840b5f10bd7e9d4a7bde849aad96e9926d827^{commit}
13:31:36 
13:31:36 stderr: fatal: ambiguous argument '9f3840b5f10bd7e9d4a7bde849aad96e9926d827^{commit}': unknown revision or path not in the working tree.
13:31:36 Use '--' to separate paths from revisions, like this:
13:31:36 'git <command> [<revision>...] -- [<file>...]'

Is there a way to fix it?
Regards
skyline00

**Comment by juliusspencer** [comment] 2016-02-02 06:32
Hi,

I have _exactly_ the same issue. The main project pulls down the commit specified with no issue and the other projects try to pull down the same commit and fail.

Thanks for any help with this!

**Comment by coder-hugo** [comment] 2016-02-27 13:48
Duplicate of #187

**Closed as completed by coder-hugo** 2016-02-27 13:48 UTC
