### ISSUE TITLE
@Library pipeline jobs post build statuses to the library repo, not the job repo

### ISSUE THREAD

**Issue by jlabonski** [jenkinsci/gitlab-plugin#526] opened 2017-03-15 20:57 UTC
### Context
- **Gitlab plugin version**: 1.4.5
- **Gitlab version**: 8.17.2
- **Jenkins version**: 2.49
- **Job type**: Pipeline

### Logs & Traces

I have to sanitize logs. Project in question is in gitlab as XXX/dispatch, in jenkins as XXX/dispatch. Jenkins library is XXX/jenkins-library

    WebHook called with url: /project/XXX/dispatch
    Notify scmSourceOwner dispatch about changes for git@YYYY:XXX/dispatch.git
    Retrieving gitlab project ids
    Retrieving the gitlab project id from remote url git@YYYY:XXX/jenkins-library.git
    Call GitLab:
      HTTP method: GET
      URL: https://YYYY/api/v3/projects/XXXX%2Fjenkins-library/repository/commits/46b83722a99425a34cd7dc1efa5e6cc7a4f5690f

### Problem description

If you use a Jenkins library retrieved via SCM, the gitlab plugin seems to get confused and sends build statuses for the pipeline job to the jenkins library repo, not the job's repo. Smells like it's using the last checkout or something from the SCM manager instead of the one from the job, since the pipeline library gets checked out after the job source.

Pipeline file: 

    properties([gitLabConnection('XXXX')])
    @Library('jenkins-library') _
    node {
    ...

Push a commit to the job in question and gitlab will report "Pipeline passed in 0 seconds" on the library tip of `master`, as defined in the `@Library` call, _not_ the actual commit that we're building for.

Library configured for retrieval via modern SCM, git.

**Comment by jlabonski** [comment] 2017-03-16 11:45
Duplicate of #523?

**Comment by pgeorgiev333** [comment] 2017-03-20 08:50
Looks like its duplicate of my defect #523

**Closed as completed** 2017-03-23 23:09 UTC

**Comment by omehegan** [comment] 2017-07-05 22:21
This was released today in version 1.4.6 of the plugin.
