### ISSUE TITLE
Environment variables not support on postbuild with "Publish build status to GitLab commit (GitLab 8.1+ required)"

### ISSUE THREAD

**Issue by hu-haibo** [jenkinsci/gitlab-plugin#502] opened 2017-02-13 09:41 UTC
- gitlab 8.10.0
- jenkins 2.7.4
- jenkins gitlab plugin 1.4.4

I'm trying to use the variable "${JOB_NAME}", but has not been parsed. 

jenkins job:
![61954b8cf3c6af7bc5f5764dd3e49bc1](https://cloud.githubusercontent.com/assets/10339929/22877822/266d7938-f212-11e6-9b6b-ff7f966c29b1.png)

gitlab build details:
![f2f9f1a874d8894d56b51f53c136050c](https://cloud.githubusercontent.com/assets/10339929/22878023/ef99715e-f212-11e6-8da5-974a8c8c0b19.png)

**Comment by omehegan** [comment] 2017-02-13 21:21
Duplicate of https://github.com/jenkinsci/gitlab-plugin/issues/446 and there is an open PR to fix it.

**Closed as completed by omehegan** 2017-02-13 21:21 UTC
