### ISSUE TITLE
Feature request: provide full access to JSON payload send by web hook

### ISSUE THREAD

**Issue by cgumpert** [jenkinsci/gitlab-plugin#439] opened 2016-10-31 22:20 UTC
Dear developers,

we are using this plugin quite successfully for a while. With growing complexity of our software, we would like to extend the tasks of our Jenkins CI system. For some of those tasks (e.g. assigning labels to merge requests automatically) we would need to have access to more information than what is currently provided as environment variables. On [this page](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/web_hooks/web_hooks.md), the information send by the GitLab web hooks is documented in very detail. As far as we understand, only a small subset of this information is provided as environment variables (e.g. gitlabSourceBranch etc) to the Jenkins jobs. Therefore our question, whether it would be possible to provide the whole JSON string received from the webhook as another environment variable?

In our opinion, extracting all the information from the JSON string into environment variables is for sure too much. But having all the information available so that we could parse the JSON string inside our jobs if needed, would be of great help to us.

Thanks

P.S. Unfortunately, I do not speak java :-(. Otherwise I would have loved to contribute this feature.

**Comment by omehegan** [comment] 2016-11-02 20:43
I like this idea, I've wanted something like this in the past. It would be especially handy in Pipeline jobs, if we just generated a Groovy map with the entire data structure in it. But this wouldn't be possible in Multibranch jobs, as far as I know.

**Comment by omehegan** [comment] 2018-08-08 01:45
Duplicate of #708.

**Closed as completed by omehegan** 2018-08-08 01:45 UTC
Labels: feature request
