### ISSUE TITLE
"No public field" error in Declarative Definition Generator

### ISSUE THREAD

**Issue by katanacrimson** [jenkinsci/gitlab-plugin#819] opened 2018-08-01 19:15 UTC
### Context
- **Gitlab plugin version**: 1.5.9
- **Gitlab version**: 11.1.2
- **Jenkins version**: 2.121.2
- **Job type**: Declarative Pipeline

### Problem description

Declarative Definition Generator - trying to generate a snippet, this is what I'm running into:

![image](https://user-images.githubusercontent.com/121707/43543292-30184aa8-9595-11e8-895b-7f10ba25edca.png)

    no public field ‘acceptMergeRequestOnSuccess’ (or getter method) found in class com.dabsquared.gitlabjenkins.GitLabPushTrigger

**Comment by omehegan** [comment] 2018-08-02 00:29
Duplicate of #805.

**Closed as completed by omehegan** 2018-08-02 00:29 UTC
