### ISSUE TITLE
HTTP enable instead of SSH default

### ISSUE THREAD

**Issue by cdenneen** [jenkinsci/gitlab-plugin#176] opened 2016-01-08 17:12 UTC
Can this plugin work over HTTP vs ssh?

git clone https://gitlab/project.git

vs 

git clone git@gitlab:project.git

**Comment by coder-hugo** [comment] 2016-02-26 21:19
I don't get your issue. The git clone stuff isn't part of the plugin this is done by the git-plugin which can be configured using a HTTPS URL.

**Comment by cdenneen** [comment] 2016-02-26 21:24
${gitlabSourceRepoURL} is not https and provides no way to do this.

**Comment by coder-hugo** [comment] 2016-02-27 14:48
Duplicate of #211

**Closed as completed by coder-hugo** 2016-02-27 14:48 UTC
