### ISSUE TITLE
500 error from Gitlab on build status updates

### ISSUE THREAD

**Issue by robbyb67** [jenkinsci/gitlab-plugin#337] opened 2016-05-27 17:08 UTC
from gitlab-plugin log:

Call GitLab:
HTTP method: GET

URL: http://kallisto/api/v3/projects/common%2Fmaven-parent/repository/commits/9aec637421a34bc267380e5b47f7d32b04ea4adf
Request headers: [
Accept = [application/json],
PRIVATE-TOKEN = [***_FILTERED**_*]
]
Mai 27, 2016 5:31:18 PM AM FEINSTEN com.dabsquared.gitlabjenkins.gitlab.GitLabClientBuilder
Got response from GitLab:
URL: http://kallisto/api/v3/projects/common%2Fmaven-parent/repository/commits/9aec637421a34bc267380e5b47f7d32b04ea4adf
Status: 500 Internal Server Error
Response headers: [
Connection = [keep-alive],
Content-Length = [48],
Content-Type = [application/json; charset=utf-8],
Date = [Fri, 27 May 2016 15:31:17 GMT],
Server = [nginx],
Status = [500 Internal Server Error],
X-Request-Id = [1ca846df-eb38-4c2f-bbb0-2feb96d54d54],
X-Runtime = [0.780938]
]
Response body: {"status":"500","error":"Internal Server Error"}

Gitlab version: 8.8.2 (community edition)
Jenkins version: 2.6
gitlab plugin version: 1.2.3

**Comment by coder-hugo** [comment] 2016-05-30 06:24
Can you please have a look to the log of GitLab for an error. A HTTP status 500 means that something on the server side went wrong. In case the client (in this case the gitlab-plugin) sends wrong data to the server the server should respond with a HTTP status 400.

**Comment by macneib** [comment] 2016-06-01 23:01
If you look at your git logs `gitlab-ctl tail` you'll see out of memory errors.  This can be fixed by,
adding swap

https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04

if gitlab is running in a docker container:you will need to run the container in privileged mode first

**Comment by omehegan** [comment] 2016-06-01 23:05
@macneib why are you assuming that this is a memory issue on the GitLab side?

**Comment by robbyb67** [comment] 2016-06-02 13:56
I cant see memory error on the gitlab side:

==> gitlab-shell/gitlab-shell.log <==
I, [2016-06-02T15:49:54.086654 #15956]  INFO -- : POST http://0.0.0.0:8080/api/v3/internal/allowed 0.32506
I, [2016-06-02T15:49:54.090140 #15956]  INFO -- : gitlab-shell: executing git command <git-upload-pack /var/opt/gitlab/git-data/repositories/common/maven-parent.git> for user with key key-19.

==> gitlab-rails/production.log <==
Started GET "/api/v3/projects/common/maven-parent/repository/commits/9aec637421a34bc267380e5b47f7d32b04ea4adf" for 127.0.0.1 at 2016-06-02 15:49:54 +0200
Processing by NamespacesController#show as JSON
  Parameters: {"id"=>"api/v3/projects/common/maven-parent/repository/commits/9aec637421a34bc267380e5b47f7d32b04ea4adf"}
Completed 500 Internal Server Error in 533ms (ActiveRecord: 39.7ms)

ActionView::MissingTemplate (Missing template opt/gitlab/embedded/service/gitlab-rails/public/404 with {:locale=>[:en], :formats=>[:json], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :haml]}. Searched in:
- "/opt/gitlab/embedded/service/gitlab-rails/app/views"
- "/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/kaminari-0.16.3/app/views"
- "/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/doorkeeper-3.1.0/app/views"
- "/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/devise-3.5.4/app/views"
- "/var/opt/gitlab/gitlab-rails/working"
- "/"
  ):
  app/controllers/application_controller.rb:144:in `render_404'
  app/controllers/namespaces_controller.rb:22:in`show'
  lib/gitlab/middleware/go.rb:16:in `call'

But maybe the errors are not visible in default logging.

**Comment by omehegan** [comment] 2016-06-02 17:14
There's no reason to assume this is a memory problem. A 500 error can indicate any number of problems on the GitLab side. In this case it looks like GitLab tried to render a template for displaying a 404 page and failed to do that, resulting in the 500. If I'm right, the question is why it was trying to give you a 404. Can you explain what type of build/update triggered this? For example, if you have things configured to merge branches automatically and then delete them, I can imagine that updating the build status after that point would fail with a 404.

**Comment by macneib** [comment] 2016-06-02 20:16
@omehegan is correct. It wasn't right to assume a memory error. Apologies.

**Comment by omorillo** [comment] 2016-06-14 21:58
@robbyb67 Any news on this issue?

**Comment by velith** [comment] 2016-06-19 11:49
I have the same issue as described with my setup. I have also tried to use a minimalistic setup of a Jenkins job as described in the readme for this plugin. I get an identical error output in the production.log as robbyb67

I have done some experiments using Postman, with my own private token (admin on Gitlab), and a GET on `/api/v3/projects/:id` works fine when using the ID of a project, but not when using NAMESPACE/PROJECT_NAME. Then the same error occurs (500 response). I tried with and without %2F for the slash between namespace and project name, as stated in the Gitlab API documentation.

To me this seems more like an issue with my setup of Gitlab than with this plugin. But why it wants to render a 404 and also fails to do so, I don't understand.

Gitlab version: 8.5.1
Jenkins version: 2.6
gitlab plugin version: 1.2.3

**Comment by sugi1987** [comment] 2016-06-21 05:16
I also got same problems returning 500 from Gitlab.
As I confirmed system log output, Jenkins gitlab-plugin just called below to get commit info at first sequence.

<pre>
GET http://{hostname}/{namespace}/api/v3/projects/{namespace}/{project_name}/repository/commits/:commithash
Notice: Within {namespace}/{project_name}, "/" is replacing "%2F".
</pre>

I guess that calling below would be expected as describing at Gltlab Docs(http://docs.gitlab.com/ce/api/repositories.html).

<pre>
GET http://{hostname}/{namespace}/api/v3/projects/:id/repository/commits/:commithash
</pre>

As with velith, when I call expected endpoint using Postman, I can get response with 200 from Gitlab.
(The gitlab-plugin must have project ":id" as well, because gitlab-hook-plugin is triggered by Gitlab's webhook with commits info.)
I can't catch whether my setup is wrong or not.

Gitlab version: 8.5.8
Jenkins version: 2.8
gitlab-plugin version: 1.2.3

**Comment by coder-hugo** [comment] 2016-06-21 07:43
> (The gitlab-plugin must have project ":id" as well, because gitlab-hook-plugin is triggered by Gitlab's webhook with commits info.)

Nope, the build status update is independent of the webhook. You can add this to a job without having the Webhook Trigger enabled and it will still notify GitLab about the build status. Also for manually triggered build this id isn't available.
Within your production.log the slash between `namespace` and `project_name` isn't replaced by %2F so I assume you have a misconfigured Apache (or another reverse proxy) in front of your GitLab that replaces %2F with a slash.

**Comment by sugi1987** [comment] 2016-06-21 11:22
> Nope, the build status update is independent of the webhook. You can add this to a job without having the webhook Trigger enabled and it will still notify GitLab about the build status. Also for manually triggered build this id isn't available.

I verified that Gitlab's webhook triggers certain Jenkins job (which sets "Publish build status to Gitlab commit" as processing after build) and this job tries to notify Gitlab using Gitlab API after build, but it calls wrong endpoint as describing above.
I guess you mean that a publishing report job can be triggered actively without Gitlab webhook's trigger (like polling repository), but in this way, can gitlab-plugin recognize project_id as well?

> Within your production.log the slash between namespace and project_name isn't replaced by %2F

Nope, As with robbyb67's system log above, the slash between namespace and project_name is also replaced by %2F.

> so I assume you have a misconfigured Apache (or another reverse proxy) in front of your GitLab that replaces %2F with a slash.

As you said, there is possibility that misconfigured frontend causes errors, but to begin with, why does gitlab-plugin try to call wrong (different from API docs) endpoint?

Thanks,

**Comment by coder-hugo** [comment] 2016-06-21 13:08
@sugi1987 I can't find a %2F with the production.log of robby67. Between the namespace and the project there is a /.
And the plugin doesn't use a wrong endpoint. You can get a single project by its namespace + project_name (see [here](http://docs.gitlab.com/ce/api/projects.html#get-single-project)). The GitLab API is kind of a REST API and the repository and its commits are sub-resources of a project. Using a REST API you will be always able to retrieve sub-resources starting from the path of their parent resource.
For the plugin the only way to figure out the project_id without using URLs that contain a %2F would mean to retrieve the complete list of projects and compare their repo URL with the one configured in the jenkins job. Depending on the GitLab size this can take ages to find the project_id.

**Comment by sugi1987** [comment] 2016-06-21 14:51
> I can't find a %2F with the production.log of robby67. Between the namespace and the project there is a /.

I apologize that I misunderstood production.log (Gitlab side) for gitlab-plugin log (Jenkins side), and also the expression of id (The ID OR NAMESPACE/PROJECT_NAME which notes that "/" has to be replaced with %2F).

> The GitLab API is kind of a REST API and the repository and its commits are sub-resources of a project. Using a REST API you will be always able to retrieve sub-resources starting from the path of their parent resource.

Thank you. I understood the reason why the URL encode is needed.

> For the plugin the only way to figure out the project_id without using URLs that contain a %2F would mean to retrieve the complete list of projects and compare their repo URL with the one configured in the Jenkins job. Depending on the GitLab size this can take ages to find the project_id.

That means regardless of the way to trigger Jenkins job (Gitlab's webhook to Jenkins job OR  Jenkins's polling to Gitlab), I have to setup reverse proxy in front of Gitlab correctly that it notifies correct id (NAMESPACE/PROJECT_NAME which notes that "/" has to be replaced with %2F) to Jenkins side.
Is this correct?

**Comment by coder-hugo** [comment] 2016-06-21 17:05
@robbyb67 It's almost correct. The gitlab-plugin already replaces the `/` with a `%2F`. The issue is that your reverse proxy (in front of GitLab) replaces this necessary `%2F` by a `/`. You have to configure your reverse proxy to not doing this. For an Apache this can be done with the [`AllowEncodedSlashes`](https://httpd.apache.org/docs/2.2/en/mod/core.html#allowencodedslashes) directive.

**Comment by coder-hugo** [comment] 2016-06-24 21:33
As already mentioned this error is not caused by the plugin but by a not properly setup GitLab. Nevertheless the plugin will use the integer projectId for all builds triggered by GitLab with the next release. Therefore I close this issue now.

**Closed as completed by coder-hugo** 2016-06-24 21:33 UTC

**Comment by gtudan** [comment] 2016-07-12 12:21
@coder-hugo That would really help! I totally agree that this is a setup bug, but I couldn't get our environment to work with this - it looks like the revers proxy passes the uri just fine, but somewhere between the workhorse and the API things get messed up.

Is there an issue for this I can track?

**Comment by velith** [comment] 2016-07-27 14:51
Updating to the latest version of the plugin (1.3.0 at present time) fixed the problem for me.

**Comment by lalmeras** [comment] 2017-01-13 19:57
For any person who encounters difficulty on this point, here's my experience with an Apache (proxy_http) + nginx + gitlab setting. In Apache, configure both:
* AllowEncodedSlashes NoDecode
* ProxyPass / http://gitlab.server/ nocanon

Without this 2 settings, requests was blocked by Apache (AllowEncodedSlashes absent or Off), %2F was replaced by '/' (AllowEncodedSlashes On), %2F was replaced by %252F (AllowEncodedSlashes NoDecode without nocanon)

With this settings, I successfully submit a commit status update.
