### ISSUE TITLE
Nullpoint exception in jenkins, Gitlab CE 8.7, gitlab-plugin:latest

### ISSUE THREAD

**Issue by eskobarba** [jenkinsci/gitlab-plugin#303] opened 2016-05-09 13:24 UTC
Seen 236 remote branches
Checking out Revision 450de3b8071aad0f8a04e18105c17bc06a3220f0 (origin/master)

> git config core.sparsecheckout # timeout=10
> git checkout -f 450de3b8071aad0f8a04e18105c17bc06a3220f0
> git rev-list e781faa4cfa1cd0f14e39091628b2abbbdf9d0c9 # timeout=10
> FATAL: null
> java.lang.NullPointerException
>     at org.jboss.resteasy.util.ReadFromStream.readFromStream(ReadFromStream.java:30)
>     at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.bufferEntity(ClientResponse.java:307)
>     at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.DefaultEntityExtractorFactory$3.extractEntity(DefaultEntityExtractorFactory.java:48)
>     at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:104)
>     at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:64)
>     at com.sun.proxy.$Proxy80.headCommit(Unknown Source)
>     at com.dabsquared.gitlabjenkins.util.CommitStatusUpdater.existsCommit(CommitStatusUpdater.java:72)
>     at com.dabsquared.gitlabjenkins.util.CommitStatusUpdater.updateCommitStatus(CommitStatusUpdater.java:37)
>     at com.dabsquared.gitlabjenkins.publisher.GitLabCommitStatusPublisher.prebuild(GitLabCommitStatusPublisher.java:33)
>     at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:837)
>     at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:832)
>     at hudson.model.Build$BuildExecution.doRun(Build.java:144)
>     at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
>     at hudson.model.Run.execute(Run.java:1738)
>     at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
>     at hudson.model.ResourceController.execute(ResourceController.java:98)
>     at hudson.model.Executor.run(Executor.java:410)
> [CHECKSTYLE] Collecting checkstyle analysis files...
> [CHECKSTYLE] Finding all files that match the pattern build/reports/*_/_.xml
> [CHECKSTYLE] Computing warning deltas based on reference build #1
> [ANALYSIS-COLLECTOR] Skipping publisher since build result is FAILURE
> Skipping Cobertura coverage report as build was not UNSTABLE or better ...
> ERROR: Build step failed with exception
> java.lang.NullPointerException
>     at org.jboss.resteasy.util.ReadFromStream.readFromStream(ReadFromStream.java:30)
>     at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.bufferEntity(ClientResponse.java:307)
>     at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.DefaultEntityExtractorFactory$3.extractEntity(DefaultEntityExtractorFactory.java:48)
>     at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:104)
>     at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:64)
>     at com.sun.proxy.$Proxy80.headCommit(Unknown Source)
>     at com.dabsquared.gitlabjenkins.util.CommitStatusUpdater.existsCommit(CommitStatusUpdater.java:72)
>     at com.dabsquared.gitlabjenkins.util.CommitStatusUpdater.updateCommitStatus(CommitStatusUpdater.java:37)
>     at com.dabsquared.gitlabjenkins.publisher.GitLabCommitStatusPublisher.perform(GitLabCommitStatusPublisher.java:45)
>     at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
>     at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
>     at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
>     at hudson.model.Build$BuildExecution.post2(Build.java:185)
>     at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
>     at hudson.model.Run.execute(Run.java:1763)
>     at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
>     at hudson.model.ResourceController.execute(ResourceController.java:98)
>     at hudson.model.Executor.run(Executor.java:410)
> Build step 'Publish build status to GitLab commit (GitLab 8.1+ required)' marked build as failure
> Finished: FAILURE

**Comment by omehegan** [comment] 2016-05-09 16:27
Dupe of https://github.com/jenkinsci/gitlab-plugin/issues/284

**Closed as completed by omehegan** 2016-05-09 16:27 UTC
