### ISSUE TITLE
Parameter gitlabMergeRequestTitle is always blank

### ISSUE THREAD

**Issue by alienspaces** [jenkinsci/gitlab-plugin#180] opened 2016-01-13 03:34 UTC
It looks like a bunch of really useful merge request information was added in this commit

https://github.com/jenkinsci/gitlab-plugin/commit/58af7ef453fd06964a30ceaf2a837b6774b77c56

Will a new release be available for this plugin soon that includes the above additions?

Would it also be possible to add gitlabMergeRequestDescription?

**Comment by shwangste** [comment] 2016-02-26 04:10
+1

**Comment by coder-hugo** [comment] 2016-02-27 14:49
Duplicate of #211

**Closed as completed by coder-hugo** 2016-02-27 14:49 UTC
