### ISSUE TITLE
Build when a change is pushed to Gitlab checkbox not persisting in Jenkins

### ISSUE THREAD

**Issue by anweiss** [jenkinsci/gitlab-plugin#395] opened 2016-08-17 19:55 UTC
## Issue

After checking the _Build when a change is pushed to Gitlab_ checkbox under _Build Triggers_ in Jenkins and successfully triggering a build from a Gitlab push, the checkbox becomes unchecked, thereby preventing subsequent pushes to Gitlab from triggering new builds.
### Context
- **Gitlab plugin version**: 1.3.0
- **Gitlab version**: CE 8.10.5 (5f47c35)
- **Jenkins version**: 2.7.2
### Logs & Traces

Logs indicated that the project "triggered for push" and runs the build successfully. It doesn't show any indication of unchecking the Build Trigger checkbox.
### Problem description

I have configured the Gitlab project Webhook to trigger new builds in Jenkins. The webhook tests successfully with an HTTP 200 and triggers a build. However, when I open the project configuration page in Jenkins, I notice that the _Build when a change is pushed to Gitlab_ box becomes unchecked. If I re-check the box and submit new builds, it will trigger the first build, but then uncheck the box again. This happens every time I test the Webhook directly or push new commits to my Gitlab repo.

**Comment by bzon** [comment] 2016-08-19 09:20
I just encountered the same issue! I'm using Jenkins 2.7.2 , Gitlab Plugin 1.3.0, Gitlab 8.10.5, using Jenkins Pipeline pugin.

This issue happens after a successful webhook trigger from Gitlab to Jenkins. The Gitlab configuration in the Pipeline job does not persist.

So far my workaround is to have a job that process Job DSL to create the job that has the Gitlab configuration, and this job generator is scheduled to run every minute and run everytime my ci job completes.

**Comment by coder-hugo** [comment] 2016-08-27 15:37
I can't reproduce this and the plugin also doesn't touch the configuration of a job. So I'd assume there is something else in your Jenkins setup that causes this trouble. May I ask you for installing the following plugin: [Support Core Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Support+Core+Plugin) in your Jenkins and generate a support bundle. This will generate a Dockerfile that can be used to generate a docker image that should contain a Jenkins with a similar setup to yours. Additionally an example configuration of a job causing this issue would be helpful.

**Comment by akrevenya** [comment] 2016-08-31 20:30
I experiencing the same issue with job(pipeline) partial configuration disappearance after triggering build from gitlab using webhook.

Jenkins: 2.20
Gitlab Plugin: 1.3.1
Gitlab: 8.5.7-ee

**Comment by hubermi** [comment] 2016-09-01 13:30
I experience the same issue, but only if I call properties, e.g. to set the gitlab configuration:
`properties ([[$class: 'GitLabConnectionProperty', gitLabConnection: 'Default']])`

It seems like this deletes all configured properties and only sets the one that have been defined in the Jenkinsfile.

**Comment by akrevenya** [comment] 2016-09-01 16:49
@hubermi Thank you. Yes, you are correct. After removing `properties ([....])` the issue went away.  But I'm still not sure if this is bug, and if it is which plugin is a culprit?

**Comment by winggundamth** [comment] 2016-09-02 05:19
But this should be fixed right? Because properties shouldn't replace all the jobs configuration but merge it instead.

**Comment by coder-hugo** [comment] 2016-09-04 19:16
Why are you using the `properties` step in a "normal" pipeline job? You can set these properties directly on the configuration page of the job. This step is thought to be used for multibranch pipeline jobs where you can't do this. So I'd say this is a misuage of the `properties` step not a bug. Btw. if this step is added to a normal pipeline job all build triggers are removed after a build not only the GitLabPushTrigger so if it's a bug this is not related to this plugin.

**Closed as completed by coder-hugo** 2016-09-04 19:16 UTC
