### ISSUE TITLE
How to trigger build on push to fork for an open MR?

### ISSUE THREAD

**Issue by ehelms** [jenkinsci/gitlab-plugin#150] opened 2015-12-07 19:08 UTC
First off, I have tried looking through existing issues and doing some testing on our setup of my own so if I missed the same issue please kindly redirect me.

We are using Gitlab 7.8.2 and 1.1.28 of this plugin. Currently, our workflow involves opening a MR from developer forks. If said MR needs updating, the developer will force push their fork and branch that the MR was opened against to update it so as to not have to re-open a MR. As far as my testing can tell, this does not invoke a rebuild of the Jenkins job to re-run the tests are a developer updates. First off, is this a possible workflow with this plugin and Gitlab ?

When I do push to my fork, I see the following in the Jenkins logs:

```
WebHook called with url: /build
Dec 07, 2015 1:55:27 PM INFO com.dabsquared.gitlabjenkins.GitLabWebHook getDynamic
WebHook called with url: /commits/0c9bbe1cbf496baa2711279da5dafb4636dbca58/status.json
Dec 07, 2015 1:55:27 PM WARNING org.eclipse.jetty.util.log.JavaUtilLog warn
Error while serving https://OMITTED/commits/0c9bbe1cbf496baa2711279da5dafb4636dbca58/status.json
java.lang.reflect.InvocationTargetException
```

Thanks,
Eric

**Comment by coder-hugo** [comment] 2016-02-27 14:34
Duplicate of #210

**Closed as completed by coder-hugo** 2016-02-27 14:34 UTC
