### ISSUE TITLE
Unable to auto merge on successful build using Jenkins CI

### ISSUE THREAD

**Issue by jejohns** [jenkinsci/gitlab-plugin#186] opened 2016-01-27 01:08 UTC
I have repos configured via the Jenkins CI service to trigger builds when a merge request is created. If I select the "Merge when build succeeds" option after creating the merge request, the merge request remains in a state where it's indefinitely waiting on a successful build result. While it's stuck in this state, Jenkins has already returned a successful result but the state of the merge request remains unchanged.

![auto_merge](https://cloud.githubusercontent.com/assets/791932/12600522/5e5bf410-c44f-11e5-82a8-5ff8e7c6b1a3.png)

I can't tell if it's a issue on the Gitlab side or the Jenkins Gitlab plugin side. I am using Gitlab 8.3.4 with Jenkins Gitlab plugin 1.1.28. I followed the instructions here for setup: http://doc.gitlab.com/ee/integration/jenkins.html

**Comment by vstriz** [comment] 2016-01-28 13:25
I'm observing exactly same thing.

**Comment by kflorence** [comment] 2016-02-01 19:34
+1

**Comment by telisior** [comment] 2016-02-02 12:28
Same problem for me.
I still observe it on GitLab 8.4.2.

**Comment by sebastienbonami** [comment] 2016-02-08 19:53
:+1:
I think the issue is on GitLab side, so I created this ticket: https://gitlab.com/gitlab-org/gitlab-ce/issues/13269

**Comment by ayufan** [comment] 2016-02-19 19:49
I did check that. The Jenkins plugin should send the `ref` (just name without the `refs/heads` or `refs/tags`) in order for Commit Status and automatic merge to work.

**Comment by WonderCsabo** [comment] 2016-02-27 13:01
I am also seeing this bug on Gitlab 8.3 and 8.5.

**Comment by ayufan** [comment] 2016-02-27 13:12
WonderCsabo: Thanks. I'll verify it once again :)

**Comment by coder-hugo** [comment] 2016-02-27 17:19
According to http://doc.gitlab.com/ce/api/commits.html#post-the-build-status-to-a-commit the ref has to be a tag or branch not the commit hash.

**Comment by coder-hugo** [comment] 2016-02-27 20:37
Was closed by accident.

**Comment by ayufan** [comment] 2016-02-28 19:30
@coder-hugo Is there anything that I can help with?

**Comment by coder-hugo** [comment] 2016-02-28 20:07
@ayufan a bit more of time to work on the plugin would be helpful :wink:
I'll hopefully fix this during my code cleanups within the next days.
I just added the last comment and the label to this issue while looking through all open issues to get an overview what needs to be done cause I'm the new lead maintainer since a few days.

**Comment by ayufan** [comment] 2016-02-28 20:38
Awesome. @coder-hugo if you need any help from GitLab side I'm more than happy to help you with that :)

**Comment by sebastienbonami** [comment] 2016-03-01 16:45
@coder-hugo I tried a quick fix and it's solving the issue. In [GitLabMergeRequest.java](https://github.com/jenkinsci/gitlab-plugin/blob/ba8246b8ed1be1dbe398baaf2d3f50b5774abd99/src/main/java/com/dabsquared/gitlabjenkins/GitLabMergeRequest.java#L69): change third parameter of `createCommitStatus` method from `objectAttributes.getLastCommit().getId()` to `objectAttributes.getSourceBranch()`. Tags should also be supported I guess.

Reference: https://github.com/jenkinsci/gitlab-plugin/pull/127#discussion_r44638193

**Comment by vstriz** [comment] 2016-03-15 15:29
Is there any update on this? I have to keep reminding my team to not press that "oh so inviting" button. This would a wonderful feature to have working...

**Closed as completed** 2016-03-18 21:00 UTC
Labels: bug
