### ISSUE TITLE
Edit / label / reassign triggers a build

### ISSUE THREAD

**Issue by pablobirukov** [jenkinsci/gitlab-plugin#696] opened 2017-12-27 16:15 UTC
### Context
- **Gitlab plugin version**: 1.5.2
- **Gitlab version**: 10.1.1
- **Jenkins version**: 2.89.1
- **Job type**: Pipeline

### Problem description

* GitLab: trigger on `Merge Request events` 
* `gitlab-plugin`: trigger on `Opened Merge Request Events` and `Push Events`

Currently, every edit of MR triggers new build. That means every reassign, added label, resolved todo leads to new build. 

Is it expected behaviour? I would expect these events to be filter out. However, looking at the data sent to Jenkins (`Recent Deliveries` page) e.g. after I reassigned an MR, it's not clear what has been changed.

If that's a bug, I can provide more info that would help to narrow the scope

**Comment by omehegan** [comment] 2018-01-17 02:59
@r00ger these events probably should not trigger a build, but I'm surprised no one else has noticed this yet. Can you follow the directions for increasing plugin logging in the User Support section of the README, and then post the log from when a build is triggered by one of these other events? I believe we can check an array of actions or causes in the plugin and skip some of them, but I need to see what the plugin is doing with that information.

**Comment by omehegan** [comment] 2018-01-17 03:03
Also, what is your setting for 'Rebuild open Merge Requests?'

**Comment by omehegan** [comment] 2018-01-17 23:19
Dupe of #633 which now has some more log data in it, so I will track this fix there.

**Closed as completed by omehegan** 2018-01-17 23:19 UTC
Labels: awaiting feedback
