### ISSUE TITLE
Pipeline changeRequest and Directive Generator broken

### ISSUE THREAD

**Issue by madduci** [jenkinsci/gitlab-plugin#876] opened 2019-01-04 07:18 UTC
## Issue

The gitlab-plugin produces a wrong result in the Pipeline Directive Generator and makes the output of the function changeRequest() false

### Context

- **Gitlab plugin version**: 1.5.11
- **Gitlab version**: 11.0.2 CE
- **Jenkins version**: 2.156
- **Job type**: Pipeline, Jenkinsfile in project repository

#### Pipeline Directive Generator Bug

When using a Jenkins Declarative Pipeline Directive Generator and selecting the option for **triggers** and selecting then **gitlab**, the expected output should be something like:

`triggers {
    gitlab(triggerOnPush: true, triggerOnMergeRequest: true, branchFilterType: 'All')
}`

but it produces as output the following error message:

> no public field 'acceptMergeRequestOnSuccess' (or getter method) found in class com.dabsquared.gitlabjenkins.GitLabPushTrigger

#### changeRequest returns false

When working with merge requests in GitLab, the conditional block

`when{
    changeRequest()
}`

evaluates always to false, but it should be evaluated as true

**Comment by omehegan** [comment] 2019-02-26 05:37
@abayer if you can give me any guidance about this reported issue, I would greatly appreciate it!

**Comment by reinholdfuereder** [comment] 2019-04-25 14:30
I think this may also be related to (or a duplicate of) #805

**Comment by joelroyer** [comment] 2019-11-19 09:56
Same problem today with a declarative pipeline (Jenkinsfile at the project root), using Gitlab Plugin 1.5.13, Jenkins 2.190.2, Gitlab 12.3 CE

**Comment by hellxz** [comment] 2020-03-14 15:00
Context:
- Jenkins ver. 2.176.2
- Gitlab plugin：1.5.12

I have seen `Build when a change is pushed to GitLab, unknown URL` at Directive Generator.
and same problem with  #805，I try to find how to write declarative pipeline script with gitlab trigger without Directive Generator.

I just only find description about triggers without `Build when a change is pushed to GitLab, unknown URL` 

The document url is <https://jenkins.io/doc/book/pipeline/syntax/#triggers>
> The triggers directive defines the automated ways in which the Pipeline should be re-triggered. For Pipelines which are integrated with a source such as GitHub or BitBucket, triggers may not be necessary as webhooks-based integration will likely already be present. The triggers currently available are cron, pollSCM and upstream.

I have no idea with it. can someone give me a doc with write triggers without Directive Generator? Thx.

**Comment by prachi-chauhan** [comment] 2023-09-25 18:15
Has this been resolved as of 2023?

**Comment by MarkEWaite** [comment] 2023-09-25 18:24
> Has this been resolved as of 2023?

As far as I can tell, it has been resolved by the changes in 

* #805 

When I open the declarative Pipeline directive generator for triggers, select "gitlab" and press the "Generate Declarative Directive" button, it creates:

```groovy
triggers {
  gitlab branchFilterType: 'All', 
    excludeBranchesSpec: '', 
    includeBranchesSpec: '', 
    noteRegex: 'Jenkins please retry a build', 
    pendingBuildName: '', 
    secretToken: '', 
    skipWorkInProgressMergeRequest: true, 
    sourceBranchRegex: '', 
    targetBranchRegex: '', 
    triggerOnApprovedMergeRequest: true, 
    triggerOpenMergeRequestOnPush: 'never'
}
```

@prachi-chauhan did you try it yourself and find an issue?  If not, could you try it yourself?  I'm closing this because it worked when I tried it.

**Closed as completed by MarkEWaite** 2023-09-25 18:24 UTC
Labels: bug
