### ISSUE TITLE
Multiscm plugin support

### ISSUE THREAD

**Issue by ibratoev** [jenkinsci/gitlab-plugin#187] opened 2016-01-28 14:26 UTC
If a CI job is configured to use the multiscm plugin (https://wiki.jenkins-ci.org/display/JENKINS/Multiple+SCMs+Plugin) then builds are not triggered properly from GitLab pushes and Merge Requests.

**Comment by froque** [comment] 2016-02-09 19:25
seems duplicate of #183

**Comment by ibratoev** [comment] 2016-02-11 14:22
Yeah, it is a dupe.

**Comment by coder-hugo** [comment] 2016-03-16 21:17
Fixed with version 1.1.31

**Closed as completed by coder-hugo** 2016-03-16 21:17 UTC
Labels: fix-pending
